// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EGVVFysEgfT6-qJvomf_hvI0YpLQtVg',
    appId: '1:325081322031:web:4f6084decf0e8071c5acda',
    messagingSenderId: '325081322031',
    projectId: 'sample-project-8f3e9',
    authDomain: 'sample-project-8f3e9.firebaseapp.com',
    storageBucket: 'sample-project-8f3e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6hfsgpZdgqk9L8vRdPzEt7vnEdNBzmA',
    appId: '1:863457149574:android:dd019a532e629ddd788707',
    messagingSenderId: '863457149574',
    projectId: 'coral-ecommerce-4d523',
    storageBucket: 'coral-ecommerce-4d523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjEgmYEfUxGs5C9BZApII_iaOW-HEvok',
    appId: '1:325081322031:ios:e110f709b40acebfc5acda',
    messagingSenderId: '325081322031',
    projectId: 'sample-project-8f3e9',
    storageBucket: 'sample-project-8f3e9.appspot.com',
    iosBundleId: 'com.example.shoppingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfjEgmYEfUxGs5C9BZApII_iaOW-HEvok',
    appId: '1:325081322031:ios:e110f709b40acebfc5acda',
    messagingSenderId: '325081322031',
    projectId: 'sample-project-8f3e9',
    storageBucket: 'sample-project-8f3e9.appspot.com',
    iosBundleId: 'com.example.shoppingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8EGVVFysEgfT6-qJvomf_hvI0YpLQtVg',
    appId: '1:325081322031:web:4f6084decf0e8071c5acda',
    messagingSenderId: '325081322031',
    projectId: 'sample-project-8f3e9',
    authDomain: 'sample-project-8f3e9.firebaseapp.com',
    storageBucket: 'sample-project-8f3e9.appspot.com',
  );

}